name: enflab
version: 1.0
profile: enflab
config-version: 2
models:
  enflab:
    +materialized: table
    bronze: { +tags: ["bronze_to_silver"] }
    silver: { +tags: ["bronze_to_silver"] }
    gold: { +tags: ["silver_to_gold"] }
seeds: { +quote_columns: false }
snapshots: {}
on-run-start:
  - "INSTALL httpfs;"
  - "LOAD httpfs;"
