global:
  scrape_interval: 15s

scrape_configs:
  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]

  - job_name: redpanda
    metrics_path: /metrics
    static_configs:
      - targets: ["redpanda:9644"]
