enflab:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /project/transform/dbt/enflab/target/enflab.duckdb
      threads: 4
      extensions: [httpfs]
      settings:
        s3_region: "{{ env_var('AWS_REGION', 'us-east-1') }}"
        s3_url_style: path
        s3_endpoint: "{{ env_var('DUCKDB_S3_ENDPOINT', 'http://minio:9000') }}"
        s3_use_ssl: false
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID', 'minio') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY', 'minio123') }}"
